# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

In this lecture, we will go through the range of important NumPy's concepts and built-in function that we will be frequently using in the coming sections. As usual, this notebook is a reference to the video lecture. You can always explore this notebook if you need help.  

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [2]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [3]:
# Lets create a Python list. 
my_list = [-1,0,1]
my_list
my_list[0]

-1

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(my_list) 
my_array
my_array[0]

-1

In [5]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9], [4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [7]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [8]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# We can give the step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [25]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [27]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [29]:
np.linspace(0,15,30) # 1-D array 

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

### `zeros()`

* We want to create an array with **all zeros**<br>

*Press shift+tab for the documentation.*

In [31]:
np.zeros(15) # 1-D with 3 elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((4,6)) #(no_row, no_col) passing a tuple

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### `ones()`

* We want to create an array with **all ones**<br>

*Press shift+tab for the documentation.*

In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones((4,6)) #(no_row, no_col) passing a tuple

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## `eye()` 
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

*Press shift+tab for the documentation.*

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [35]:
np.random.rand(3) # 1-D array with three elements

array([0.96354088, 0.89695435, 0.32580356])

In [39]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.83691376, 0.92675035],
       [0.80570807, 0.64508301],
       [0.10825692, 0.01478343]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [40]:
np.random.randn(5)

array([ 1.98278231,  0.03103314,  0.7662666 ,  1.71495358, -0.27800492])

In [21]:
np.random.randn(4,4) # no tuple, each dimension as a separate argument

array([[-0.19510557,  1.11071072, -1.4823238 ,  0.22163069],
       [-0.83215988,  0.89786005, -1.58374755,  0.45936113],
       [ 0.10825114,  0.28382467,  0.15052097, -0.22077727],
       [-0.18417952,  0.88135759,  0.02033709, -1.70748824]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [47]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

94

In [48]:
np.random.randint(1,500,10) #returns ten random int,

array([ 32, 409,  58, 236,  79, 265,  98, 222, 379, 287])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [49]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [50]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
array_ranint

array([19, 31, 13, 13,  3, 21, 27, 96, 92, 90])

#### `Reshape()`
Returns an array containing the same data with a new shape.

In [57]:
reshape_test=array_arange.reshape(4,4) # any other num will give error
reshape_test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [59]:
array_ranint

array([19, 31, 13, 13,  3, 21, 27, 96, 92, 90])

In [61]:
array_ranint.max()

96

In [62]:
array_ranint.min()

3

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [63]:
array_ranint.argmax() # index starts from 0

7

In [64]:
array_ranint.argmin()

4

### Attributes
* `size, shape, dtype` 

In [65]:
# Lets take vector array, array_arange 
array_arange.shape
#reshape_test.shape

(16,)

In [66]:
# Size of the array 
array_arange.size

16

In [67]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [71]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
array_arange.reshape(4,4).shape

(4, 4)

In [73]:
array_arange.reshape(16,1).shape

(16, 1)

In [47]:
array_arange.reshape(1,16).shape

(1, 16)

## Indexing & slicing of 1-D arrays (vectors)

In [74]:
# Lets create a simple 1-D NumPy array.
# (we can use arange() as well.) 
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [75]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [76]:
# Getting value at certain index
array_1d[0]

-10

In [77]:
# Getting a range value
array_1d[0:3], array_1d
# array_1d is included in the out to compare and understand

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [78]:
# Using -ve index 
array_1d[-2], array_1d
# array_1d is included in the out to compare and understand

(106, array([-10,  -2,   0,   2,  17, 106, 200]))

In [79]:
# Using -ve index for a range 
array_1d[1:-2], array_1d # 1 inclusive and -2 exclusive in this case

(array([-2,  0,  2, 17]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [80]:
# Getting up-to and from certain index -- remember index starts from '0'
# (no need to give start and stop indexes)
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [81]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [82]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [83]:
array_2d= np.arange(24)
array_2d.shape = (6,4) #array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [84]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [16]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [85]:
# To get an individual element value at row = 5 and column = 2
array_2d[5,2]

22

In [89]:
# another way 
row = 5
column = 2
array_2d[row, column]

22

In [86]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [92]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner 
#[row:row, column:column] [From 0 row to 1 row, From 0 column to 1 column]
# array_2d[0:2,0:2] is same as array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [11]:
array_2d[2:4,2:4] # inner slice [From 2 row to 3 row, From 2 column to 3 column]

array([[10, 11],
       [14, 15]])