### Broadcasting
### Arithmetic operations
### Math Functions: `sum()`, `max()`, `min()`, `sqrt()`, `std()`, `sin()`, `log()`

In [2]:
import numpy as np

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [3]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [4]:
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [5]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [7]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [8]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [9]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [10]:
array_2d[[1, 2, 3]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# We can use any order
array_2d[[3,0,1]]

array([[  1.,   1.,   1.,   1.],
       [300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.]])

In [12]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
# grabbing rows
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [15]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [36]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can apply condition such as >, <, == etc

In [38]:
array_1d > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [28]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

Lets create a mask to **filter out the even numbers in "array_1d"**

In [39]:
array_1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [40]:
0 == array_1d % 2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [45]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = 0 == array_1d % 2 
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [48]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

array([ 2,  4,  6,  8, 10])

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [49]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

array([0, 1, 2, 3, 4])

In [50]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [51]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [52]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [53]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\1371265232.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [54]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\1491116826.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #[0, 1, 2, 3, 4]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [55]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [56]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [27]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [29]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [17]:
#18a:
# To avoid overwriting the output, please code here 

In [59]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
#18b:
# To avoid overwriting the output, please code here 

In [60]:
array_2d[3:, 2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [42]:
#18c:
# To avoid overwriting the output, please code here 

In [61]:
array_2d[5,4] # array_2d[5][4]

29

In [44]:
#18d:
# To avoid overwriting the output, please code here 

In [62]:
array_2d[:3,1:2] # array_2d[:3,1:3] for col 1 and 2 

array([[ 1],
       [ 6],
       [11]])

In [46]:
#18e:
# To avoid overwriting the output, please code here 

In [63]:
array_2d[2,:] # array_2d[2:3,:] will give the same output

array([10, 11, 12, 13, 14])

In [48]:
#18f:
# To avoid overwriting the output, please code here 

In [64]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [65]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Calculate the sum of all the numbers in array_2d?**

In [40]:
# To avoid overwriting the output, please code here 
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
array_2d.sum()

435

In [68]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

**Calculate sum of all the rows and columns in array_2d.**

In [52]:
# To avoid overwriting the output, please code here 

In [69]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**Calculate the standard deviation of the values in array_2d.**

In [54]:
# To avoid overwriting the output, please code here 

In [70]:
array_2d.std()

8.65544144839919

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [56]:
# To avoid overwriting the output, please code here 

In [71]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [74]:
array_2d % 3 != 0

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [69]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [75]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

In [76]:
# log function
np.log(arr)
# warning for inf

C:\Users\HP\AppData\Local\Temp\ipykernel_1548\1473819699.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])