# Part-1

In [1]:
# import numpy library
import numpy as np

In [2]:
# create a Python list. 
myList = [-1, 0, 2]
myList, myList[0]

([-1, 0, 2], -1)

In [3]:
#create a numpy array, using np.array()
myArray = np.array(myList)
myArray, type(myArray), myArray[2]

(array([-1,  0,  2]), numpy.ndarray, 2)

In [4]:
# Lets create and cast a list of list to generate 2-D array 
myList = [[1,2,3],[4,5,6],[7,8,9], [4, 5, 9]]
myMatrix_one = np.array(myList)
myMatrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [5]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

# arange()

In [6]:
# similar to range() in Python, not including 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#We can give the step
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [8]:
#We can give the step and type
np.arange(2, 11, 2, dtype = float)

array([ 2.,  4.,  6.,  8., 10.])

# linspace()

In [9]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 7, 7)

array([1., 2., 3., 4., 5., 6., 7.])

In [10]:
# Lets find the step size with "retstep" which returns the array and the step size and create a 1-D
myLinspace = np.linspace(1, 5, 10, retstep=True)
myLinspace
#myLinspace[1]

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

# zeros()

In [11]:
np.zeros(10) # 1-D with 3 elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5)) #(no_row, no_col) passing a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ones()

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# eye()

In [15]:
np.eye(10)*100

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.]])

# Random

In [16]:
#rand()
np.random.rand(3) # 1-D array with three elements

array([0.85934362, 0.17280433, 0.15981667])

In [17]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.0785545 , 0.29875491],
       [0.04309589, 0.91623667],
       [0.07113788, 0.19904984]])

In [18]:
#randn()
np.random.randn(3)

array([-1.29746007,  0.01078501,  0.76910907])

In [19]:
np.random.randn(4,4) # no tuple, each dimension as a separate argument

array([[ 1.1511785 , -0.47521497,  0.29022658,  0.45440395],
       [-0.43478803, -0.19880825,  0.23674965, -1.1312129 ],
       [-0.52464504,  1.16427363,  0.61192148,  0.23701024],
       [ 0.75669732, -0.87226025,  2.31680671,  0.68320031]])

In [20]:
#randint()
np.random.randint(1,10) #returns one random int, 1 inclusive, 100 exclusive

5

# Array Methods & Attributes

# Methods

In [21]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
array_ranint = np.random.randint(0,100,10)
array_ranint

array([35, 61, 72,  1, 70, 48, 68, 22, 57, 64])

In [23]:
array_arange.reshape(4,4) # reshape()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
array_ranint.min() # min()

1

In [25]:
array_ranint.max() # max()

72

In [26]:
array_ranint.argmin() #To find the index locations of max and min values in array argmin()

3

In [27]:
array_ranint.argmax() # To find the index locations of max and min values in array argmax()

2

# Attributes

In [28]:
array_arange.shape
#reshape_test.shape

(16,)

In [29]:
# Size of the array 
array_arange.size

16

In [30]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [31]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
array_arange.reshape(4,4).shape

(4, 4)

# Indexing & slicing of 1-D arrays (vectors)

In [33]:
# Lets create a simple 1-D NumPy array.
# (we can use arange() as well.) 
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [34]:
# Getting value at certain index
array_1d[0]

-10

In [35]:
# Getting a range value
array_1d[0:3], array_1d
# array_1d is included in the out to compare and understand

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [36]:
# Using -ve index for a range 
array_1d[1:-2], array_1d # 1 inclusive and -2 exclusive in this case

(array([-2,  0,  2, 17]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [37]:
# Getting up-to and from certain index -- remember index starts from '0'
# (no need to give start and stop indexes)
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [38]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102
array_1d

array([-102,   -2,    0,    2,   17,  106,  200])

# Indexing & slicing 2-D arrays (matrices)

In [39]:
array_2d= np.arange(24)
array_2d.shape = (6,4) #array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [41]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [42]:
# To get an individual element value at row = 5 and column = 2
array_2d[5,2]

22

In [43]:
# another way 
row = 5
column = 2
array_2d[row, column]

22

In [44]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [45]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner 
#[row:row, column:column] [From 0 row to 1 row, From 0 column to 1 column]
# array_2d[0:2,0:2] is same as array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [46]:
array_2d[2:4,2:4] # inner slice [From 2 row to 3 row, From 2 column to 3 column]

array([[10, 11],
       [14, 15]])

# Part-2

In [48]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#broadcast
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [68]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [73]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [76]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [78]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [79]:
array_2d[[0, 2, 3]]

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [80]:
# We can use any order
array_2d[[3,0,1]]

array([[  1.,   1.,   1.,   1.],
       [300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.]])

In [84]:
# lets try another matrix
array_3d = np.arange(24)
array_3d.shape = (6,4)
array_3d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
# grabbing rows
array_3d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [90]:
# grabbing columns
#array_3d[:,3:2]
array_3d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [91]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
array_1d > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [93]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [94]:
array_1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [95]:
0 == array_1d % 2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [96]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = 0 == array_1d % 2 
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [107]:
#array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]] it's print only True value. like 2,4,6
array_1d[mod_2_mask_1d] 

array([ 2,  4,  6,  8, 10])

# NumPy Operations

Arithmetic operations

In [108]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [109]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [110]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [111]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [112]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

C:\Users\Rifat Ahmed\AppData\Local\Temp\ipykernel_8772\1371265232.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [113]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

C:\Users\Rifat Ahmed\AppData\Local\Temp\ipykernel_8772\1491116826.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr #[0, 1, 2, 3, 4]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [114]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [115]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

# Universal functions

In [116]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [117]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [118]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [119]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [120]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [121]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [122]:
array_2d[3:, 2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [125]:
#array_2d[5,4] 
array_2d[5][4]

29

In [127]:
#for col 1 and 2 
#array_2d[:3,1:2] 
array_2d[:3,1:3] 

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [128]:
array_2d[2,:] # array_2d[2:3,:] will give the same output

array([10, 11, 12, 13, 14])

In [129]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [130]:
# To avoid overwriting the output, please code here 
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [131]:
array_2d.sum()

435

In [132]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


In [133]:
array_2d.std()

8.65544144839919

In [134]:
array_2d % 3 != 0

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [135]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [136]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

In [137]:
# log function
np.log(arr)
# warning for inf

C:\Users\Rifat Ahmed\AppData\Local\Temp\ipykernel_8772\1473819699.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])